DELETE FROM users_roles;
DELETE FROM roles;

INSERT INTO roles (uuid, name, created_date_time)
VALUES (UUID(), 'ADMINISTRATOR', CURRENT_TIMESTAMP),
       (UUID(), 'MANAGER', CURRENT_TIMESTAMP),
       (UUID(), 'RECEPTIONIST', CURRENT_TIMESTAMP),
       (UUID(), 'HOUSEKEEPING', CURRENT_TIMESTAMP),
       (UUID(), 'USER', CURRENT_TIMESTAMP);