name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issue
        uses: peter-evans/assign-issue@v2
        with:
          assignees: radostinDragiev
