name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto-assign
        uses: kentaro-m/auto-assign-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          assignees: "RadostinDragiev"
