name: Deploy after push to main

on:
  push:
    branches: [ "main" ]

jobs:
  publish-deploy:
    name: Publish to DockerHun and deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/hotel-manager
          VERSION=${{ github.sha }}
          
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

#      - name: Trigger Render Deploy
#        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Trigger Render Deploy
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true