name: Auto Assign Pull Request

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
        - uses: kentaro-m/auto-assign-action@v2.0.0